# This is a basic workflow to test pooch on python 3.11 for PR https://github.com/scipy/scipy/pull/15607

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11-dev"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install packages
        run: pip install pooch

      # Runs a single command using the runners shell
      - name: Run a one-line script to check if pooch installation works fine
        run: python -c 'import pooch; import os; pooch.file_hash(os.path.join(os.path.abspath("."), "README.md"))'
